//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dbfabricaModel", "pedido_ibfk_1", "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DolcePeccato.DTO.cliente), "pedido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DolcePeccato.DTO.pedido), true)]
[assembly: EdmRelationshipAttribute("dbfabricaModel", "produtoxpromocao_ibfk_2", "produto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DolcePeccato.DTO.produto), "produtoxpromocao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DolcePeccato.DTO.produtoxpromocao), true)]
[assembly: EdmRelationshipAttribute("dbfabricaModel", "produtoxpromocao_ibfk_1", "promocao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DolcePeccato.DTO.promocao), "produtoxpromocao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DolcePeccato.DTO.produtoxpromocao), true)]
[assembly: EdmRelationshipAttribute("dbfabricaModel", "produtoxpedido_ibfk_2", "produto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DolcePeccato.DTO.produto), "produtoxpedido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DolcePeccato.DTO.produtoxpedido), true)]

#endregion

namespace DolcePeccato.DTO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbfabricaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbfabricaEntities object using the connection string found in the 'dbfabricaEntities' section of the application configuration file.
        /// </summary>
        public dbfabricaEntities() : base("name=dbfabricaEntities", "dbfabricaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbfabricaEntities object.
        /// </summary>
        public dbfabricaEntities(string connectionString) : base(connectionString, "dbfabricaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbfabricaEntities object.
        /// </summary>
        public dbfabricaEntities(EntityConnection connection) : base(connection, "dbfabricaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cliente> cliente
        {
            get
            {
                if ((_cliente == null))
                {
                    _cliente = base.CreateObjectSet<cliente>("cliente");
                }
                return _cliente;
            }
        }
        private ObjectSet<cliente> _cliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<pedido> pedido
        {
            get
            {
                if ((_pedido == null))
                {
                    _pedido = base.CreateObjectSet<pedido>("pedido");
                }
                return _pedido;
            }
        }
        private ObjectSet<pedido> _pedido;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<produto> produto
        {
            get
            {
                if ((_produto == null))
                {
                    _produto = base.CreateObjectSet<produto>("produto");
                }
                return _produto;
            }
        }
        private ObjectSet<produto> _produto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<produtoxpromocao> produtoxpromocao
        {
            get
            {
                if ((_produtoxpromocao == null))
                {
                    _produtoxpromocao = base.CreateObjectSet<produtoxpromocao>("produtoxpromocao");
                }
                return _produtoxpromocao;
            }
        }
        private ObjectSet<produtoxpromocao> _produtoxpromocao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<promocao> promocao
        {
            get
            {
                if ((_promocao == null))
                {
                    _promocao = base.CreateObjectSet<promocao>("promocao");
                }
                return _promocao;
            }
        }
        private ObjectSet<promocao> _promocao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<produtoxpedido> produtoxpedido
        {
            get
            {
                if ((_produtoxpedido == null))
                {
                    _produtoxpedido = base.CreateObjectSet<produtoxpedido>("produtoxpedido");
                }
                return _produtoxpedido;
            }
        }
        private ObjectSet<produtoxpedido> _produtoxpedido;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocliente(cliente cliente)
        {
            base.AddObject("cliente", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the pedido EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopedido(pedido pedido)
        {
            base.AddObject("pedido", pedido);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the produto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproduto(produto produto)
        {
            base.AddObject("produto", produto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the produtoxpromocao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToprodutoxpromocao(produtoxpromocao produtoxpromocao)
        {
            base.AddObject("produtoxpromocao", produtoxpromocao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the promocao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopromocao(promocao promocao)
        {
            base.AddObject("promocao", promocao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the produtoxpedido EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToprodutoxpedido(produtoxpedido produtoxpedido)
        {
            base.AddObject("produtoxpedido", produtoxpedido);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbfabricaModel", Name="cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cliente object.
        /// </summary>
        /// <param name="clienteID">Initial value of the ClienteID property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static cliente Createcliente(global::System.Int64 clienteID, global::System.String nome)
        {
            cliente cliente = new cliente();
            cliente.ClienteID = clienteID;
            cliente.Nome = nome;
            return cliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ClienteID
        {
            get
            {
                return _ClienteID;
            }
            set
            {
                if (_ClienteID != value)
                {
                    OnClienteIDChanging(value);
                    ReportPropertyChanging("ClienteID");
                    _ClienteID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClienteID");
                    OnClienteIDChanged();
                }
            }
        }
        private global::System.Int64 _ClienteID;
        partial void OnClienteIDChanging(global::System.Int64 value);
        partial void OnClienteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ramo
        {
            get
            {
                return _Ramo;
            }
            set
            {
                OnRamoChanging(value);
                ReportPropertyChanging("Ramo");
                _Ramo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ramo");
                OnRamoChanged();
            }
        }
        private global::System.String _Ramo;
        partial void OnRamoChanging(global::System.String value);
        partial void OnRamoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rua
        {
            get
            {
                return _Rua;
            }
            set
            {
                OnRuaChanging(value);
                ReportPropertyChanging("Rua");
                _Rua = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rua");
                OnRuaChanged();
            }
        }
        private global::System.String _Rua;
        partial void OnRuaChanging(global::System.String value);
        partial void OnRuaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.String _Numero;
        partial void OnNumeroChanging(global::System.String value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Complemento
        {
            get
            {
                return _Complemento;
            }
            set
            {
                OnComplementoChanging(value);
                ReportPropertyChanging("Complemento");
                _Complemento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Complemento");
                OnComplementoChanged();
            }
        }
        private global::System.String _Complemento;
        partial void OnComplementoChanging(global::System.String value);
        partial void OnComplementoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cep
        {
            get
            {
                return _Cep;
            }
            set
            {
                OnCepChanging(value);
                ReportPropertyChanging("Cep");
                _Cep = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cep");
                OnCepChanged();
            }
        }
        private global::System.String _Cep;
        partial void OnCepChanging(global::System.String value);
        partial void OnCepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bairro
        {
            get
            {
                return _Bairro;
            }
            set
            {
                OnBairroChanging(value);
                ReportPropertyChanging("Bairro");
                _Bairro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bairro");
                OnBairroChanged();
            }
        }
        private global::System.String _Bairro;
        partial void OnBairroChanging(global::System.String value);
        partial void OnBairroChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbfabricaModel", "pedido_ibfk_1", "pedido")]
        public EntityCollection<pedido> pedido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<pedido>("dbfabricaModel.pedido_ibfk_1", "pedido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<pedido>("dbfabricaModel.pedido_ibfk_1", "pedido", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbfabricaModel", Name="pedido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pedido : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new pedido object.
        /// </summary>
        /// <param name="pedidoID">Initial value of the PedidoID property.</param>
        /// <param name="clienteID">Initial value of the ClienteID property.</param>
        /// <param name="dataPedido">Initial value of the DataPedido property.</param>
        public static pedido Createpedido(global::System.Int64 pedidoID, global::System.Int64 clienteID, global::System.DateTime dataPedido)
        {
            pedido pedido = new pedido();
            pedido.PedidoID = pedidoID;
            pedido.ClienteID = clienteID;
            pedido.DataPedido = dataPedido;
            return pedido;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PedidoID
        {
            get
            {
                return _PedidoID;
            }
            set
            {
                if (_PedidoID != value)
                {
                    OnPedidoIDChanging(value);
                    ReportPropertyChanging("PedidoID");
                    _PedidoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PedidoID");
                    OnPedidoIDChanged();
                }
            }
        }
        private global::System.Int64 _PedidoID;
        partial void OnPedidoIDChanging(global::System.Int64 value);
        partial void OnPedidoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ClienteID
        {
            get
            {
                return _ClienteID;
            }
            set
            {
                if (_ClienteID != value)
                {
                    OnClienteIDChanging(value);
                    ReportPropertyChanging("ClienteID");
                    _ClienteID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClienteID");
                    OnClienteIDChanged();
                }
            }
        }
        private global::System.Int64 _ClienteID;
        partial void OnClienteIDChanging(global::System.Int64 value);
        partial void OnClienteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataPedido
        {
            get
            {
                return _DataPedido;
            }
            set
            {
                OnDataPedidoChanging(value);
                ReportPropertyChanging("DataPedido");
                _DataPedido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataPedido");
                OnDataPedidoChanged();
            }
        }
        private global::System.DateTime _DataPedido;
        partial void OnDataPedidoChanging(global::System.DateTime value);
        partial void OnDataPedidoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbfabricaModel", "pedido_ibfk_1", "cliente")]
        public cliente cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("dbfabricaModel.pedido_ibfk_1", "cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("dbfabricaModel.pedido_ibfk_1", "cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cliente> clienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("dbfabricaModel.pedido_ibfk_1", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cliente>("dbfabricaModel.pedido_ibfk_1", "cliente", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbfabricaModel", Name="produto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class produto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new produto object.
        /// </summary>
        /// <param name="produtoID">Initial value of the ProdutoID property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="preco">Initial value of the Preco property.</param>
        /// <param name="estoque">Initial value of the Estoque property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        public static produto Createproduto(global::System.Int64 produtoID, global::System.String nome, global::System.Decimal preco, global::System.Int64 estoque, global::System.String tipo)
        {
            produto produto = new produto();
            produto.ProdutoID = produtoID;
            produto.Nome = nome;
            produto.Preco = preco;
            produto.Estoque = estoque;
            produto.Tipo = tipo;
            return produto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProdutoID
        {
            get
            {
                return _ProdutoID;
            }
            set
            {
                if (_ProdutoID != value)
                {
                    OnProdutoIDChanging(value);
                    ReportPropertyChanging("ProdutoID");
                    _ProdutoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProdutoID");
                    OnProdutoIDChanged();
                }
            }
        }
        private global::System.Int64 _ProdutoID;
        partial void OnProdutoIDChanging(global::System.Int64 value);
        partial void OnProdutoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ingradientes
        {
            get
            {
                return _Ingradientes;
            }
            set
            {
                OnIngradientesChanging(value);
                ReportPropertyChanging("Ingradientes");
                _Ingradientes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ingradientes");
                OnIngradientesChanged();
            }
        }
        private global::System.String _Ingradientes;
        partial void OnIngradientesChanging(global::System.String value);
        partial void OnIngradientesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Foto
        {
            get
            {
                return StructuralObject.GetValidValue(_Foto);
            }
            set
            {
                OnFotoChanging(value);
                ReportPropertyChanging("Foto");
                _Foto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Foto");
                OnFotoChanged();
            }
        }
        private global::System.Byte[] _Foto;
        partial void OnFotoChanging(global::System.Byte[] value);
        partial void OnFotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Preco
        {
            get
            {
                return _Preco;
            }
            set
            {
                OnPrecoChanging(value);
                ReportPropertyChanging("Preco");
                _Preco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Preco");
                OnPrecoChanged();
            }
        }
        private global::System.Decimal _Preco;
        partial void OnPrecoChanging(global::System.Decimal value);
        partial void OnPrecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Estoque
        {
            get
            {
                return _Estoque;
            }
            set
            {
                OnEstoqueChanging(value);
                ReportPropertyChanging("Estoque");
                _Estoque = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estoque");
                OnEstoqueChanged();
            }
        }
        private global::System.Int64 _Estoque;
        partial void OnEstoqueChanging(global::System.Int64 value);
        partial void OnEstoqueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbfabricaModel", "produtoxpromocao_ibfk_2", "produtoxpromocao")]
        public EntityCollection<produtoxpromocao> produtoxpromocao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<produtoxpromocao>("dbfabricaModel.produtoxpromocao_ibfk_2", "produtoxpromocao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<produtoxpromocao>("dbfabricaModel.produtoxpromocao_ibfk_2", "produtoxpromocao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbfabricaModel", "produtoxpedido_ibfk_2", "produtoxpedido")]
        public EntityCollection<produtoxpedido> produtoxpedido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<produtoxpedido>("dbfabricaModel.produtoxpedido_ibfk_2", "produtoxpedido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<produtoxpedido>("dbfabricaModel.produtoxpedido_ibfk_2", "produtoxpedido", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbfabricaModel", Name="produtoxpedido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class produtoxpedido : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new produtoxpedido object.
        /// </summary>
        /// <param name="produtoXPedidoID">Initial value of the ProdutoXPedidoID property.</param>
        /// <param name="pedidoID">Initial value of the PedidoID property.</param>
        /// <param name="produtoID">Initial value of the ProdutoID property.</param>
        public static produtoxpedido Createprodutoxpedido(global::System.Int64 produtoXPedidoID, global::System.Int64 pedidoID, global::System.Int64 produtoID)
        {
            produtoxpedido produtoxpedido = new produtoxpedido();
            produtoxpedido.ProdutoXPedidoID = produtoXPedidoID;
            produtoxpedido.PedidoID = pedidoID;
            produtoxpedido.ProdutoID = produtoID;
            return produtoxpedido;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProdutoXPedidoID
        {
            get
            {
                return _ProdutoXPedidoID;
            }
            set
            {
                if (_ProdutoXPedidoID != value)
                {
                    OnProdutoXPedidoIDChanging(value);
                    ReportPropertyChanging("ProdutoXPedidoID");
                    _ProdutoXPedidoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProdutoXPedidoID");
                    OnProdutoXPedidoIDChanged();
                }
            }
        }
        private global::System.Int64 _ProdutoXPedidoID;
        partial void OnProdutoXPedidoIDChanging(global::System.Int64 value);
        partial void OnProdutoXPedidoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PedidoID
        {
            get
            {
                return _PedidoID;
            }
            set
            {
                if (_PedidoID != value)
                {
                    OnPedidoIDChanging(value);
                    ReportPropertyChanging("PedidoID");
                    _PedidoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PedidoID");
                    OnPedidoIDChanged();
                }
            }
        }
        private global::System.Int64 _PedidoID;
        partial void OnPedidoIDChanging(global::System.Int64 value);
        partial void OnPedidoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProdutoID
        {
            get
            {
                return _ProdutoID;
            }
            set
            {
                if (_ProdutoID != value)
                {
                    OnProdutoIDChanging(value);
                    ReportPropertyChanging("ProdutoID");
                    _ProdutoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProdutoID");
                    OnProdutoIDChanged();
                }
            }
        }
        private global::System.Int64 _ProdutoID;
        partial void OnProdutoIDChanging(global::System.Int64 value);
        partial void OnProdutoIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbfabricaModel", "produtoxpedido_ibfk_2", "produto")]
        public produto produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<produto>("dbfabricaModel.produtoxpedido_ibfk_2", "produto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<produto>("dbfabricaModel.produtoxpedido_ibfk_2", "produto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<produto> produtoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<produto>("dbfabricaModel.produtoxpedido_ibfk_2", "produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<produto>("dbfabricaModel.produtoxpedido_ibfk_2", "produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbfabricaModel", Name="produtoxpromocao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class produtoxpromocao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new produtoxpromocao object.
        /// </summary>
        /// <param name="produtoXPromocaoID">Initial value of the ProdutoXPromocaoID property.</param>
        /// <param name="promocaoID">Initial value of the PromocaoID property.</param>
        /// <param name="produtoID">Initial value of the ProdutoID property.</param>
        public static produtoxpromocao Createprodutoxpromocao(global::System.Int64 produtoXPromocaoID, global::System.Int64 promocaoID, global::System.Int64 produtoID)
        {
            produtoxpromocao produtoxpromocao = new produtoxpromocao();
            produtoxpromocao.ProdutoXPromocaoID = produtoXPromocaoID;
            produtoxpromocao.PromocaoID = promocaoID;
            produtoxpromocao.ProdutoID = produtoID;
            return produtoxpromocao;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProdutoXPromocaoID
        {
            get
            {
                return _ProdutoXPromocaoID;
            }
            set
            {
                if (_ProdutoXPromocaoID != value)
                {
                    OnProdutoXPromocaoIDChanging(value);
                    ReportPropertyChanging("ProdutoXPromocaoID");
                    _ProdutoXPromocaoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProdutoXPromocaoID");
                    OnProdutoXPromocaoIDChanged();
                }
            }
        }
        private global::System.Int64 _ProdutoXPromocaoID;
        partial void OnProdutoXPromocaoIDChanging(global::System.Int64 value);
        partial void OnProdutoXPromocaoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PromocaoID
        {
            get
            {
                return _PromocaoID;
            }
            set
            {
                if (_PromocaoID != value)
                {
                    OnPromocaoIDChanging(value);
                    ReportPropertyChanging("PromocaoID");
                    _PromocaoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PromocaoID");
                    OnPromocaoIDChanged();
                }
            }
        }
        private global::System.Int64 _PromocaoID;
        partial void OnPromocaoIDChanging(global::System.Int64 value);
        partial void OnPromocaoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProdutoID
        {
            get
            {
                return _ProdutoID;
            }
            set
            {
                if (_ProdutoID != value)
                {
                    OnProdutoIDChanging(value);
                    ReportPropertyChanging("ProdutoID");
                    _ProdutoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProdutoID");
                    OnProdutoIDChanged();
                }
            }
        }
        private global::System.Int64 _ProdutoID;
        partial void OnProdutoIDChanging(global::System.Int64 value);
        partial void OnProdutoIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbfabricaModel", "produtoxpromocao_ibfk_2", "produto")]
        public produto produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<produto>("dbfabricaModel.produtoxpromocao_ibfk_2", "produto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<produto>("dbfabricaModel.produtoxpromocao_ibfk_2", "produto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<produto> produtoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<produto>("dbfabricaModel.produtoxpromocao_ibfk_2", "produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<produto>("dbfabricaModel.produtoxpromocao_ibfk_2", "produto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbfabricaModel", "produtoxpromocao_ibfk_1", "promocao")]
        public promocao promocao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<promocao>("dbfabricaModel.produtoxpromocao_ibfk_1", "promocao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<promocao>("dbfabricaModel.produtoxpromocao_ibfk_1", "promocao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<promocao> promocaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<promocao>("dbfabricaModel.produtoxpromocao_ibfk_1", "promocao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<promocao>("dbfabricaModel.produtoxpromocao_ibfk_1", "promocao", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbfabricaModel", Name="promocao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class promocao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new promocao object.
        /// </summary>
        /// <param name="promocaoID">Initial value of the PromocaoID property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="dataInicio">Initial value of the DataInicio property.</param>
        public static promocao Createpromocao(global::System.Int64 promocaoID, global::System.String nome, global::System.DateTime dataInicio)
        {
            promocao promocao = new promocao();
            promocao.PromocaoID = promocaoID;
            promocao.Nome = nome;
            promocao.DataInicio = dataInicio;
            return promocao;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PromocaoID
        {
            get
            {
                return _PromocaoID;
            }
            set
            {
                if (_PromocaoID != value)
                {
                    OnPromocaoIDChanging(value);
                    ReportPropertyChanging("PromocaoID");
                    _PromocaoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PromocaoID");
                    OnPromocaoIDChanged();
                }
            }
        }
        private global::System.Int64 _PromocaoID;
        partial void OnPromocaoIDChanging(global::System.Int64 value);
        partial void OnPromocaoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataInicio
        {
            get
            {
                return _DataInicio;
            }
            set
            {
                OnDataInicioChanging(value);
                ReportPropertyChanging("DataInicio");
                _DataInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInicio");
                OnDataInicioChanged();
            }
        }
        private global::System.DateTime _DataInicio;
        partial void OnDataInicioChanging(global::System.DateTime value);
        partial void OnDataInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataFim
        {
            get
            {
                return _DataFim;
            }
            set
            {
                OnDataFimChanging(value);
                ReportPropertyChanging("DataFim");
                _DataFim = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataFim");
                OnDataFimChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataFim;
        partial void OnDataFimChanging(Nullable<global::System.DateTime> value);
        partial void OnDataFimChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbfabricaModel", "produtoxpromocao_ibfk_1", "produtoxpromocao")]
        public EntityCollection<produtoxpromocao> produtoxpromocao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<produtoxpromocao>("dbfabricaModel.produtoxpromocao_ibfk_1", "produtoxpromocao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<produtoxpromocao>("dbfabricaModel.produtoxpromocao_ibfk_1", "produtoxpromocao", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
